### PR TITLE
Drop notebook builds

### PR DESCRIPTION
**Pull request by psschwei**
### Summary

Fixes #1046 
Drop notebook builds

### CODE REVIEW

**Comment by psschwei** [comment]
>lint: commands[1]> pylint -rn quantum_serverless tests
************* Module quantum_serverless.core.decorators
>quantum_serverless/core/decorators.py:85:11: E1123: Unexpected keyword argument 'object_refs' in function call (unexpected-keyword-arg)

That's an odd failure for a PR that doesn't touch the code...

**Comment by IceKhan13** [comment]
looks like ray has changed `wait` function signature

**Comment by IceKhan13** [comment]
looks like it is called `waitables` now 🤔 

https://github.com/ray-project/ray/blob/2b57ee9bcf48dc665aac487dafd0044b65bc652c/python/ray/_private/worker.py#L2753

**Comment by IceKhan13** [comment]
here is PR with the change https://github.com/ray-project/ray/commit/7b33cd8c5e5cc84c2995da00cefe16f462c15881#diff-bec668cc316d34704cdc3e37dd4ce18e4e87764fdf2c28b1504478c7eb8291deL2685

**Comment by IceKhan13** [comment]
Fix is in main. Merge main and you should be good to go

**Review by IceKhan13 — APPROVED** [review]

**Pull request merged**
