### PR TITLE
mount cert volumes to init container

### LINKED ISSUE #776: Ray cluster: TLS is blocking workers to join cluster
### Steps to reproduce the problem

Deploy ray cluster with tls enabled

### What is the current behavior?

Workers are handing in non-ready status on `wait for GCS to be ready;`

In init container `wait-gcs-ready`

This check is always failing
>       until ray health-check --address cluster-user-994c3d3c-head-svc.quantum-serverless.svc.cluster.local:6379 > /dev/null 2>&1; do echo wait for GCS to be ready; sleep 5; done

Therefore workers cannot connect to head node a.k.a join cluster.

### What is the expected behavior?

Workers should be able to join cluster with TLS enabled

### PR DESCRIPTION
**Pull request by akihikokuroda**
### Summary
fix #776

### Details and comments
The init container needs the certificates to communicate to the head node.  The volume mounts were missing.

### CODE REVIEW

**Comment by akihikokuroda** [comment]
@IceKhan13 I think that this fix the issue.  You can try by adding the lines in the configmap template and reinstall the helm chart.

**Review by psschwei — APPROVED** [review]
(not for this PR) Is it possible to make the logs for that init container a bit more verbose? Right now if there's an error they just repeat "wait for GCS to be ready" over and over. I didn't see the `ray health-check` command in our repo though, so maybe not...

**Comment by IceKhan13** [comment]
checking :)

**Review by IceKhan13 — APPROVED** [review]
Awesome! it's working. Workers are connected to head and workload is distributed to them.

**Comment by IceKhan13** [comment]
Thank you @akihikokuroda!

**Comment by akihikokuroda** [comment]
> Is it possible to make the logs for that init container a bit more verbose?

@psschwei The initContainer is probably added by the Ray operator so the changes may need in the kuberay.  I'll take a look.

**Pull request merged**
