### PR TITLE
add filter option to logs

### PR DESCRIPTION
**Pull request by akihikokuroda**
### Summary
fix: #947 

### Details and comments
This adds filteredLogs function that filters the log before return to the caller.  It uses rex expressing for include and exclude the log lines.

### CODE REVIEW

**Comment by IceKhan13** [comment]
I'm wondering, can we somehow disable those logs on a ray side? 🤔

**Comment by akihikokuroda** [comment]
I was looking for a way to change the default logging level of the Ray but I couldn't find so far.  The default is `INFO`.  If we can find a way to change it, we can eliminate some log entries.

**Comment by psschwei** [comment]
looks like we can configure the ray logger, but it requires a bit of config: https://docs.ray.io/en/releases-2.5.1/ray-observability/user-guides/configure-logging.html#using-rays-logger

**Comment by IceKhan13** [comment]
> looks like we can configure the ray logger, but it requires a bit of config: https://docs.ray.io/en/releases-2.5.1/ray-observability/user-guides/configure-logging.html#using-rays-logger

Hm, maybe we should go with this option? 

If I'm understanding it correctly it require to specify logger for driver process and for tasks. But how can we hide it from user and do it automatically? 🤔 

We can hide all logs setup behind something like
```python
QuantumServerless.setup()
```

where behind the scenes we will do 
```python
def logger_setup():
     logger = logging.getLogger("ray")
    ...

class QuantumServerless:
     def setup(cls):
         logger_setup()
         ray.init({"setup_hook": logger_setup})

```

But it is still extra call by user. Hmmm 🤔

**Review by IceKhan13 — APPROVED** [review]
Let's merge this one and we can think how to move it to cluster configs later

**Pull request merged**
