### PR TITLE
🏗️  IBM Cloud deployment improvements

### PR DESCRIPTION
**Pull request by Tansito**
### Summary

**THIS PR IS UNDER WORK**

Testing our current configuration in IBM Cloud I could make it work but with some slightly changes.

### Details and comments

Due to the differences between the deployment in local vs IBM Cloud I made more dynamic our Ingress configuration with the purpose to be able to support AWS too without the need to change the template if not only the values (as a normal user would do).

- I removed `nginxconfig` in favor of adding those annotations in `ray-ingress`.
- `ray-ingress` now is more dynamic so you can add the annotations and host configuration through the values file.
- In `RayCluster` removed unused ports.
- Fix in terraform values that now are required by the project: `machine_type`, `workers_per_zone`, `disable_pse`...
- Removed `helm` integration in `terraform` due to now helm release requires values from the cluster after its creation (investigating if we can obtain them).

### Resources

- [IBM Cloud](https://cloud.ibm.com/docs/containers?topic=containers-managed-ingress-setup#managed-ingress-steps-resource) 
- [NGINX Controller annotations](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#rewrite)

**By now I only tested this configuration in IBM Cloud and without KeyCloak. In the next days I will continue testing keycloak and make it work with local (AWS next iteration).**

### CODE REVIEW

**Comment by Tansito** [comment]
From #246 I would like to know your opinions about the changes that I'm doing @psschwei @akihikokuroda 🙏 

Once time I finish to make the project fully work in IBM Cloud and localhost I will open the PR.

**Comment by akihikokuroda** [comment]
I looked through the changes.  It looks good to me.

**Comment by psschwei** [comment]
I got an error when I tried installing on an IKS cluster from this PR:

```console
$ helm -n ray install quantum-serverless --create-namespace .
Error: INSTALLATION FAILED: Ingress.extensions "ray-ingress" is invalid: spec: Invalid value: 
[]networking.IngressRule(nil): either `defaultBackend` or `rules` must be specified
```

**Comment by Tansito** [comment]
How this PR got a bit stale I close it in favour of #447 where I continue this work.

**Pull request closed without merging**
