### PR TITLE
Bump default python to 3.10

### PR DESCRIPTION
**Pull request by psschwei**
### Summary

Part of #1251 

Use Python 3.10 for gateway / ray node images

### Details and comments

xref #1258

### CODE REVIEW

**Review by Tansito — COMMENTED** [review]
I would like to propose some minor changes too:

- Use IMAGE_PY_VERSION=py310 as default [here](https://github.com/psschwei/quantum-serverless/blob/bump-gateway-python/Dockerfile-ray-node#L1)
- Use py310 as default [here](https://github.com/psschwei/quantum-serverless/blob/a438ad6b1697af6e34982e45ea35bdeb8d76984c/gateway/main/settings.py#L312)
  - We should update version now that I saw it 😂 
- Update to py310 [here](https://github.com/psschwei/quantum-serverless/blob/a438ad6b1697af6e34982e45ea35bdeb8d76984c/CONTRIBUTING.md?plain=1#L221)
- Update to py310 [here](https://github.com/psschwei/quantum-serverless/blob/a438ad6b1697af6e34982e45ea35bdeb8d76984c/charts/quantum-serverless/values.yaml#L56)
- Update to py310 [here](https://github.com/psschwei/quantum-serverless/blob/a438ad6b1697af6e34982e45ea35bdeb8d76984c/docker-compose.yaml#L5)
- Update to py310 [here](https://github.com/psschwei/quantum-serverless/blob/a438ad6b1697af6e34982e45ea35bdeb8d76984c/client/tests/resources/test-compose.yaml#L4)
- About this change I'm not sure but we probably should change to py310 [here too](https://github.com/psschwei/quantum-serverless/blob/a438ad6b1697af6e34982e45ea35bdeb8d76984c/.github/workflows/update-component-versions.yaml#L44)

And these were all the references that I found, sorry for the big text 😅

**Review by Tansito — APPROVED** [review]
LGTM Paul, thank you!

**Comment by Tansito** [comment]
I just rerun the test, it seems it had a timeout but let's see if we need to take a look more in-depth.

**Comment by psschwei** [comment]
Yeah, something is not right in one or more of the experimental jobs... will check tomorrow

**Comment by psschwei** [comment]
well, think I found why it's timing out...

**Comment by psschwei** [comment]
made a few more changes, so @Tansito @akihikokuroda can you check again?

**Comment by psschwei** [comment]
All good now

**Review by akihikokuroda — APPROVED** [review]

**Review by Tansito — APPROVED** [review]

**Pull request merged**
