### PR TITLE
Fix docker lint action

### LINKED ISSUE #1220: Fix docker lint action
### Steps to reproduce the problem

From #1200 and #1199 has an error due to the last `vim` installation

### What is the expected behavior?

`vim` should be pinned and fix the linter

### PR DESCRIPTION
**Pull request by Tansito**
### Summary

Fix #1220 

### Details and comments

Pinned `vim` version to fix the error in the Docker lint action

### CODE REVIEW

**Comment by psschwei** [comment]
For whatever reason, the Kubernetes test appears to be stuck trying to run jobs...

image

Not sure what exactly is going on there...

**Comment by Tansito** [comment]
Yep, it started to happen in all the `pull_requests` today 🤔 

Let me know if you need help with it, @psschwei

**Comment by psschwei** [comment]
Maybe we should add `--full-trace` to the pytest call in the k8s test to see if that shows us any additional info?

**Comment by Tansito** [comment]
I don't see any problem I suppose 🤷‍♂️

**Comment by Tansito** [comment]
At least linter errors disappeared 😂

**Comment by psschwei** [comment]
Seems like the issue is with nbmake v1.5 ....

**Comment by psschwei** [comment]
We broke something...

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 55, in inner
    resp = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 270, in request
    api_response = self.client.call_api(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 279, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': '66ed4609-46aa-49ce-b2da-ded45a9f6080', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Warning': '299 - "unknown field \\"spec\\""', 'X-Kubernetes-Pf-Flowschema-Uid': '1af9dae2-d851-4714-915e-8b17a1e786f4', 'X-Kubernetes-Pf-Prioritylevel-Uid': '535ac6ae-8ea1-41f2-a4fe-4e34f58b62c4', 'Date': 'Mon, 12 Feb 2024 22:04:03 GMT', 'Content-Length': '212'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the API version in the data (ray.io/v1) does not match the expected API version (ray.io/v1alpha1)","reason":"BadRequest","code":400}\n'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/manage.py", line 47, in <module>
    main()
  File "/usr/src/app/manage.py", line 43, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/api/management/commands/schedule_queued_jobs.py", line 71, in handle
    job = execute_job(job)
  File "/usr/src/app/api/schedule.py", line 72, in execute_job
    compute_resource = create_ray_cluster(
  File "/usr/src/app/api/ray.py", line 233, in create_ray_cluster
    response = raycluster_client.create(body=cluster_data, namespace=namespace)
  File "/usr/local/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 119, in create
    return self.request('post', path, body=body, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 57, in inner
    raise api_exception(e)
kubernetes.dynamic.exceptions.BadRequestError: 400
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': '66ed4609-46aa-49ce-b2da-ded45a9f6080', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Warning': '299 - "unknown field \\"spec\\""', 'X-Kubernetes-Pf-Flowschema-Uid': '1af9dae2-d851-4714-915e-8b17a1e786f4', 'X-Kubernetes-Pf-Prioritylevel-Uid': '535ac6ae-8ea1-41f2-a4fe-4e34f58b62c4', 'Date': 'Mon, 12 Feb 2024 22:04:03 GMT', 'Content-Length': '212'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the API version in the data (ray.io/v1) does not match the expected API version (ray.io/v1alpha1)","reason":"BadRequest","code":400}\n'
Original traceback: 
  File "/usr/local/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 55, in inner
    resp = func(self, *args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/kubernetes/dynamic/client.py", line 270, in request
    api_response = self.client.call_api(

  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,

  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(

  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,

  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 279, in POST
    return self.request("POST", url,

  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 238, in request
    raise ApiException(http_resp=r)
```

**Comment by psschwei** [comment]
looks like something in #1121 is breaking us

**Comment by akihikokuroda** [comment]
@psschwei @Tansito  I'll take a look.

**Comment by Tansito** [comment]
Oh wow, good catch @akihikokuroda ! (and really good test @psschwei 😄) I'm going just to use this pull request to fix it

**Comment by Tansito** [comment]
Yeah, but they are other ones haha. I suppose that it's due to the last change, I will take a look in a couple of minutes 👍

**Comment by Tansito** [comment]
Checks passed! 🎉

**Review by psschwei — APPROVED** [review]

**Pull request merged**
