### PR TITLE
Issue 842 | Gateway: do not delete compute resource

### LINKED ISSUE #842: Gateway: do not delete `ComputeResource` on job update, deactivate instead
### What is the expected enhancement?

Gateway: do not delete `ComputeResource` on job update, deactivate instead.

This will allow us to keep information about program association to specific compute resource.

### PR DESCRIPTION
**Pull request by IceKhan13**
### Summary

Gateway: do not delete compute resource model, just deactivate it

### Details and comments

Closes #842

### CODE REVIEW

**Review by psschwei — COMMENTED** [review]
We probably can drop the `RAY_CLUSTER_NO_DELETE_ON_COMPLETE` envvar from #794 with this change, right ?

**Review by akihikokuroda — APPROVED** [review]
LGTM

**Comment by IceKhan13** [comment]
@psschwei this change only saves (prevent from removal) information about compute resource in db. Ray cluster itself is deleted anyway. Therefore `RAY_CLUSTER_NO_DELETE_ON_COMPLETE` is still needed

**Review by psschwei — APPROVED** [review]

**Review by Tansito — APPROVED** [review]
LGTM! 😄 

Btw @IceKhan13 just a question that came to my mind. Has it sense to add an `updated` field for a similar reason that we added it to the `Job`? I don't think we will need to monitor `ComputeResources` but just asking.

**Pull request merged**
