### PR TITLE
Gateway docker refactorization

### LINKED ISSUE #311: Improve Dockerfile configuration for gateway
### What is the expected enhancement?

The current Dockerfile configuration that we are using has some differences from our current Dockerfiles. The idea es review it and sync it with the rest of images configuration of the project.

### PR DESCRIPTION
**Pull request by Tansito**
### Summary

Fix #311 

### Details and comments

- Moved gateway's Dockerfile to the `/infrastructure` folder
- Migrated github actions to use the new folder
- Sync gateway's Dockerfile with repository
- Added repository to the `docker-compose`
- Completed the configuration for `docker-compose` & `docker-compose-dev`

### CODE REVIEW

**Review by psschwei — COMMENTED** [review]
Not sure if this is something on my end or not, but the dev docker compose didn't work for me...

```console
$ docker-compose -f docker-compose-dev.yml up
[+] Running 6/6
 ✔ keycloak 5 layers [⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                12.1s 
   ✔ ac10f00499d5 Pull complete                                                                     3.2s 
   ✔ 96d53117c12e Pull complete                                                                     3.3s 
   ✔ 1d929376eb7f Pull complete                                                                     6.3s 
   ✔ 93e1e1b6d192 Pull complete                                                                     6.3s 
   ✔ f353ba0db29e Pull complete                                                                    11.5s 
[+] Building 0.0s (0/1)                                                                                  
[+] Building 0.0s (0/0)                                                                                  
[+] Building 0.1s (2/2)                                                                                  
 => [internal] load .dockerignore                                                                   0.1s
 => => transferring context: 255B                                                                   0.0s
 => [internal] load build definition from Dockerfile-notebook                                       0.1s
[+] Building 0.1s (0/2)                                                                                  
 => [internal] load build definition from Dockerfile                                                0.1s
[+] Building 0.2s (2/4)                                                                                  
 => [internal] load .dockerignore                                                                   0.1s
[+] Building 0.3s (4/4) FINISHED                                                                         
 => [internal] load .dockerignore                                                                   0.1s
 => => transferring context: 255B                                                                   0.0s 
 => [internal] load build definition from Dockerfile-notebook                                       0.1s
 => => transferring dockerfile: 544B                                                                0.0s
 => CANCELED [internal] load metadata for docker.io/jupyter/base-notebook:python-3.9                0.2s
 => [auth] jupyter/base-notebook:pull token for registry-1.docker.io                                0.0s
failed to solve: failed to read dockerfile: open /home/docker/tmp/buildkit-mount2718546413/Dockerfile: no such file or directory
```

**Comment by Tansito** [comment]
🤔 I will take a look as soon as I can

**Review by akihikokuroda — APPROVED** [review]
@Tansito LGTM!  Thanks!

**Review by psschwei — APPROVED** [review]
everything builds fine for me!

**Pull request merged**
