### PR TITLE
Version bump 0.1.0

### PR DESCRIPTION
**Pull request by IceKhan13**
### Summary

Update to version 0.1.0 for release

### CODE REVIEW

**Review by psschwei — APPROVED** [review]
:partying_face:

**Review by pacomf — APPROVED** [review]

**Review by akihikokuroda — APPROVED** [review]

**Comment by psschwei** [comment]
Shoot, just noticed something -- looks like a bunch of the notebooks still have the provider host as localhost instead of gateway...

**Comment by psschwei** [comment]
I'm going to submit a PR to update them (maybe we should patch that in?)

**Comment by akihikokuroda** [comment]
I wonder in what environment the `localhost` works.  I always have to change to `gateway`.

**Comment by IceKhan13** [comment]
I think we should have it as env variable or something like that. And provide this env variable in notebook as `"http://gateway:8000/"`.

```python
GatewayProvider(
    host=os.environ.get("GATEWAY_HOST", "http://localhost:8000/")
)
```

**Comment by psschwei** [comment]
You're going to test my grepping / sed skills with that one :smiley:

**Comment by akihikokuroda** [comment]
I want to make the password for the docker compose and the helm same, too.   But it can be next time.

**Comment by psschwei** [comment]
@akihikokuroda which password(s)?

**Comment by akihikokuroda** [comment]
The password of the gateway.

**Comment by psschwei** [comment]
For helm, would we change that in the keycloak password: https://github.com/Qiskit-Extensions/quantum-serverless/blob/0129ca95703adef53210256ea4ca45b08dca4fb0/infrastructure/helm/quantumserverless/values.yaml#L238 ?

I may be missing something obvious (been a long day :tired_face:), but that was the only user/passw0rd combo I saw in the values ...

**Comment by akihikokuroda** [comment]
@psschwei Yes, it seems correct.

**Comment by psschwei** [comment]
ok, cool, thanks -- I'll update that in my PR too

**Pull request merged**
