### PR TITLE
add clarifying message for failed jobs with no logs

### LINKED ISSUE #852: Gateway: when job failed and logs are empty, add clarifying message.
### What is the expected enhancement?

When job failed and logs are empty, add clarifying message in logs that something went wrong internally. Possibly provide metadata, so user have some understanding that error is acknowledged.

### PR DESCRIPTION
**Pull request by david-alber**
### Summary
closes #852 

* adding functionality (`check_logs`) to enhance the logs of a failed job with no logs with an error message that acknowledges the failure.
* adding respective unit tests and testing the expected behavior when the job status is updated.

### CODE REVIEW

**Comment by akihikokuroda** [comment]
@david-alber Thanks for your contribution.  It looks good to me!

**Review by akihikokuroda — APPROVED** [review]
LGTM!   Thanks!

**Review by IceKhan13 — APPROVED** [review]
Thank you @david-alber !

**Comment by david-alber** [comment]
_yey_ Thanks @IceKhan13 @akihikokuroda This was fun!!!
 Looking forward to the next one

**Pull request merged**
