### PR TITLE
gateway / scheduler refactor protptype

### PR DESCRIPTION
**Pull request by akihikokuroda**
### Summary
Prototype for #1033 

### Details and comments
This is on top of PR https://github.com/Qiskit-Extensions/quantum-serverless/pull/1077.  The changes for this prototype are in the last commit.

The changes are:

1. wrap the entry point sent to Ray. it sends a notification to the gateway when the entry point completes execution. It eliminates the polling of the ray job status.
2. put a signal listener for Job db changes. It can check if a Job to be scheduled and it some resources to be cleaned up.

### CODE REVIEW

**Comment by akihikokuroda** [comment]
This is a quick prototype.  There are a lot of things to clean up.  Please take look.  Thanks!

**Comment by IceKhan13** [comment]
ok, I think we need to have some kind of development branch to merge dependent PRs there. Otherwise we have bunch of PRs that sits in queue.

**Comment by akihikokuroda** [comment]
I can make this independent (based on the current main).  It can show better what are changes.

**Comment by psschwei** [comment]
> I can make this independent (based on the current main).

big +1 for this :smile:

**Comment by akihikokuroda** [comment]
PR is recreated based on current main branch in #1084. Closing.

**Pull request closed without merging**
