### PR TITLE
Library: qiskit torch trainer

### PR DESCRIPTION
**Pull request by IceKhan13**
### Summary

Qiskit trainer for parallel QPU utilization using Qiskit Runtime Sessions

### Details and comments

Example of usage
```python
from quantum_serverless.library.train import (
    QiskitScalingConfig,
    QiskitTorchTrainer,
    get_runtime_session,
)


def loop(config):
    dataset_shard = session.get_dataset_shard("train")

    runtime_sessions = get_runtime_sessions(config) # this will give you session with dedicated backend for current worker
    qnn = create_qnn(Sampler(session=runtime_sessions[0]))
    ...


scaling_config = QiskitScalingConfig(
    num_workers=3,
    resource_filtering={
        "qpu1": {"simulator": True}, # all filters that goes to `QiskitRuntimeServier.backends` method
        "qpu2": {"simulator": True},
    },
    allow_overbooking=True # allow same backend assigned to multiple workers
)
runtime_service = QiskitRuntimeService(...)

trainer = QiskitTorchTrainer(
    train_loop_per_worker=loop,
    qiskit_runtime_service_account=runtime_service.active_account(), # TODO: fix to accept QiskitRuntimeService object
    scaling_config=scaling_config,
    datasets={"train": train_dataset}
)
trainer.fit()

```

TODOs:
- [x] multiple session per worker
- [x] tests
- [x] documentation
- [x] move to `library` module

References:
Program example https://github.com/Qiskit-Extensions/quantum-serverless/blob/chore/qiskit-for-ray-train/docs/tutorials/source_files/train.py
Tutorial notebook to run above program: https://github.com/Qiskit-Extensions/quantum-serverless/blob/chore/qiskit-for-ray-train/docs/tutorials/08_distributed_qml.ipynb

### CODE REVIEW

**Comment by IceKhan13** [comment]
@ElePT ⬆️

**Review by ElePT — COMMENTED** [review]
Thanks @IceKhan13! I think that this PR is a good starting point. We have identified 2 additional requirements that we would like to see in this Trainer. The idea is to be able to parallelize a workflow that uses, let's say, 2 different QPUs with concrete coupling maps. For this means, we would need:

1. A way to define groups of resources in the `QiskitScalingConfig`. I would suggest having something like this:

```
# in trainer.py
@dataclass
class QiskitScalingConfig(ScalingConfig):
    """Scaling configuration for trainer uses Qiskit Runtime service."""

    resource_filtering: dict = None

--------------------------------------

# in user code
# specify resource group handle + filtering conditions per group of resources
# the number of resources per group is not specify here

resource_filtering = {
    "gpu_a": {"num_qubits": 2, "coupling_map": [[0,1],[1,2]]},
    "gpu_b": {"num_qubits": 3, "simulator": True},
}

scaling_config = QiskitScalingConfig(num_workers=2, resource_filtering=resource_filtering)
```

Where the `resource_filtering` dictionary would be used as args to `QiskitRuntimeService.backends()`. 

2. An extension of the `get_runtime_session()` method to assign multiple resources per worker. This could be done through the `train_loop_config` and look like this:
```
trainer = QiskitTorchTrainer(
    train_loop_per_worker=train_loop,
    qiskit_runtime_service_account=runtime_service.active_account(),
    scaling_config=scaling_config,
    datasets={"train": train_ds},
    # the resource assignment config specifies the number of resources per group per worker needed.
    # in this example we want 1 of type qpu_a and 2 of type qpu_b per worker (2 workers)
    train_loop_config={"resource_assignment": {"gpu_a":1, "gpu_b":1}, "other_config": None}
)
```

These two steps would allow to have a training loop that looks like this:
```
def train_loop(config):
    """Test training loop."""
    ...
    # if not enough backends to be selected --> get runtime sessions should throw an error
    session_a, session_b = get_runtime_sessions(config)
     sampler = CuttingSampler(     
        ThreadedSampler(session_a),  
        ThreadedSampler(session_bb)
    )    
    model = create_model(sampler) 
    model = train.torch.prepare_model(model)
    ...
```

**Comment by IceKhan13** [comment]
@ElePT updated description + added example.

Program example https://github.com/Qiskit-Extensions/quantum-serverless/blob/chore/qiskit-for-ray-train/docs/tutorials/source_files/train.py
Tutorial notebook to run above program: https://github.com/Qiskit-Extensions/quantum-serverless/blob/chore/qiskit-for-ray-train/docs/tutorials/08_distributed_qml.ipynb

Let me know if I missed anything?

**Comment by IceKhan13** [comment]
closing due to no activity

**Pull request closed without merging**
