### PR TITLE
Add action for version updates

### LINKED ISSUE #1061: Ease version updates
### What is the expected enhancement?

Currently we are manually update version number in 11 files!

We need to have a script or action that automatically bumps versions and create PR with updates

### PR DESCRIPTION
**Pull request by psschwei**
### Summary

Fixes #1061 

Update component versions for next release via Github Action.

### Details and comments

Sample of changed files:
```
$ git status
On branch auto-update-version
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   charts/qs-observability/Chart.yaml
        modified:   charts/quantum-serverless/Chart.lock
        modified:   charts/quantum-serverless/Chart.yaml
        modified:   charts/quantum-serverless/charts/gateway/Chart.yaml
        modified:   charts/quantum-serverless/charts/gateway/values.yaml
        modified:   charts/quantum-serverless/charts/jupyter/Chart.yaml
        modified:   charts/quantum-serverless/charts/repository/Chart.yaml
        modified:   charts/quantum-serverless/values.yaml
        modified:   client/quantum_serverless/VERSION.txt
        modified:   docker-compose.yaml
        modified:   docs/deployment/cloud.rst

no changes added to commit (use "git add" and/or "git commit -a")
```

(compare to files changes in #1063)

### CODE REVIEW

**Comment by IceKhan13** [comment]
I was expecting happier face expression from `feelsgood` than :feelsgood:

**Comment by psschwei** [comment]
> just go to actions, click `run workflow` and specify version to update to. And it will create PR automatically

To do that, we need an admin for the Qiskit-Extensions org to create a Github token with the appropriate permissions on the repo... not sure @IceKhan13 if you know who to prod to get such a token...

With just the script, I can make it do everything up to opening the PR, but we'd still have to manually create the PR on github.

**Comment by psschwei** [comment]
Action added. Note it won't work until we get the appropriate access token.

**Comment by IceKhan13** [comment]
I think we do not even need 
```
token: ${{ secrets.GITHUB_TOKEN }}
```
default for this action is `GITHUB_TOKEN` anyway :)

**Comment by psschwei** [comment]
That could be (I had to add a token to test it locally, but that's probably more a quirk of running locally than anything else... will take it out)

**Comment by IceKhan13** [comment]
should we give it a go?

**Review by IceKhan13 — APPROVED** [review]

**Comment by psschwei** [comment]
it should be safe to run the action whenever... it'll just cut a PR, but said PR will still need to be reviewed before it merges, so we shouldn't be able to shoot ourselves in the foot...

**Pull request merged**
