### PR TITLE
add Loki in helm and docker-compose

### LINKED ISSUE #281: Install logging aggregator into the system (Loki)
### What is the expected behavior?

Install logging aggregator into the system:
- helm chart
- docker-compose

Epic https://github.com/Qiskit-Extensions/quantum-serverless/issues/174

### PR DESCRIPTION
**Pull request by akihikokuroda**
### Summary
Fix #281 

### Details and comments

Loki is installed in [single-binary configuration](https://grafana.com/docs/loki/latest/installation/helm/install-monolithic/) by default.

### CODE REVIEW

**Comment by psschwei** [comment]
docker-compose seems to work fine, but one question: what's the user/password?

**Comment by akihikokuroda** [comment]
@psschwei Thanks for trying.  I just verified the containers are up and running for the docker-compose so I haven't tried to login.  The user id and password should be `admin` / `admin` according to the doc.

**Comment by psschwei** [comment]
Thanks!
One more question: on the helm install for k8s, what's the service for the dashboard?

**Comment by akihikokuroda** [comment]
@psschwei Is it about the dashboard of Grafana?  The helm chart doesn't have the Grafana yet.  I put the Grafana in the docker-compose because I pick it up from the [Getting started](https://grafana.com/docs/loki/latest/getting-started/) for the Loki.  I'll add Grafana to the helm install in my next PR.

**Review by IceKhan13 — APPROVED** [review]

**Review by psschwei — APPROVED** [review]
LGTM

**Pull request merged**
