### PR TITLE
Version bump 0.7.1

### PR DESCRIPTION
**Pull request by IceKhan13**
### Summary

Version bump 0.7.1

### CODE REVIEW

**Comment by IceKhan13** [comment]
After this one https://github.com/Qiskit-Extensions/quantum-serverless/pull/1060

**Comment by psschwei** [comment]
I wonder if bumping setup-helm to v3 fixes the helm error...

**Comment by psschwei** [comment]
actually, need to bump https://github.com/Qiskit-Extensions/quantum-serverless/blob/main/.github/actions/helm-lint/action.yaml#L20 to helm/chart-testing-action@v2.5.0

**Comment by psschwei** [comment]
helm issued _should_ be fixed by #1070

**Comment by psschwei** [comment]
we'll have to close / reopen this once the helm PR merges so this one picks up those changes

**Comment by IceKhan13** [comment]
we will merge helm linter fix and update this branch from main

**Comment by psschwei** [comment]
or merge #1071 :laughing:

**Comment by psschwei** [comment]
image

:partying_face: :partying_face:

**Review by Tansito — APPROVED** [review]

**Pull request merged**
