### PR TITLE
Issue 932 | Client: drop state handler class

### LINKED ISSUE #932: Client: drop `StateHandler`
### What is the expected enhancement?

Drop `StateHandler` class as it is not used anywhere and we do not have plans to use it. 
This will lift a requirement to have redis and managing redis dependencies.

### PR DESCRIPTION
**Pull request by IceKhan13**
### Summary

Drop state handler class

### Details and comments

Closes #932

### CODE REVIEW

**Comment by psschwei** [comment]
Does this mean we no longer need redis on the helm / docker installs? :pray:

**Comment by IceKhan13** [comment]
Yes! I'm cutting it off now! 🕺

**Comment by psschwei** [comment]
Can we also drop the docker compose files?

**Review by psschwei — APPROVED** [review]
:tada: :tada: :tada: 

Looks like we already dropped from docker compose a while ago (which I guess I missed)

**Pull request merged**
