### PR TITLE
Bug: cluster wait bug

### PR DESCRIPTION
**Pull request by IceKhan13**
### Summary

Bug: cluster wait bug

### CODE REVIEW

**Comment by IceKhan13** [comment]
classic infinite loop

**Comment by IceKhan13** [comment]
Closing as duplicate of https://github.com/Qiskit-Extensions/quantum-serverless/pull/711

**Comment by Tansito** [comment]
@IceKhan13 should we create a 0.2.1 release today for this to deploy it? 🤔

**Comment by psschwei** [comment]
I'd vote yes -- this seems like a fix we should get in

**Comment by Tansito** [comment]
I'm creating another one more patch that we are going to need. We can create it in our meeting today.

**Pull request closed without merging**
