### PR TITLE
CatalogEntry API

### PR DESCRIPTION
**Pull request by akihikokuroda**
### Summary
Part of #1170 

### Details and comments
This PR adds [ModelView APIs](https://github.com/Qiskit-Extensions/quantum-serverless/issues/1170#issuecomment-1917931921) for CatalogEntry. 

The list method will be enhanced to handle the query string for `title`, `description` and `tags`.

### CODE REVIEW

**Comment by akihikokuroda** [comment]
@IceKhan13 Yes, please.  I'll have follow up PR.

**Comment by psschwei** [comment]
This is probably my ignorance of django, but where/how do these APIs get specified? Or do they just get created automatically?

```
POST:api/v1/catalog_entries/ - create
GET:api/v1/catalog_entries/ - list
GET:api/v1/catalog_entries/{id}/ - get
UPDATE:api/v1/catalog_entries/{id}/ - update
PATCH:api/v1/catalog_entries/{id}/ - partial update
DELETE:api/v1/catalog_entries/{id}/ - delete
```

**Comment by Tansito** [comment]
I didn't look at the PR yet so I'm going to talk in general. Using the `ViewSet` the class generates automatically the end-points for you taking into account the methods that you declare:

https://www.django-rest-framework.org/api-guide/viewsets/

**Comment by akihikokuroda** [comment]
@psschwei Yes, It is created by using `ModelViewSet`

**Comment by akihikokuroda** [comment]
The second commit has 
```
POST:api/v1/programs/to_catalog 
```
and query string support for
```
GET:api/v1/catalog_entries/?{field}={included string}
```

**Review by IceKhan13 — APPROVED** [review]

**Pull request merged**
