### PR TITLE
Add tox as development requirement

### LINKED ISSUE #854: `tox` is not listed as a requirement anywhere
Was setting up a new venv and wasn't able to run the tests because `tox` hadn't been installed... probably should add it to all the requirements-dev.txt files...

### PR DESCRIPTION
**Pull request by psschwei**
Fixes #854

### CODE REVIEW

**Review by IceKhan13 — APPROVED** [review]

**Review by Tansito — APPROVED** [review]
Thanks @psschwei ! One question here, should we start pinning versions even for `dev` requirements, @IceKhan13 , @psschwei ?

**Comment by psschwei** [comment]
> should we start pinning versions even for `dev` requirements

:thinking: pinning makes things more reproducible / stable, but these are for building, so it might also be nice to be bleeding edge and/or pick up patches/fixes a little quicker ... I could go either way

**Comment by Tansito** [comment]
Well, in general we are relatively fast with updates with `renovate`. From time to time we got stuck in a version but I suppose it's something common. I don't have a strong opinion, either (feel free to merge it).

**Comment by psschwei** [comment]
Let's merge this and then pin them
(I did notice some weird stuff with using the most recent version of tox, which is why I had to do https://github.com/Qiskit-Extensions/quantum-serverless/pull/856/commits/f66909bace3b03b88f3672538ff81aef5bc512ce ... but I don't seem to be able to find the failed tests right now for some reason)

**Pull request merged**
