### PR TITLE
Add circuit-knitting-toolbox to jupyter notebook image

### PR DESCRIPTION
**Pull request by psschwei**
### Summary

Add CKT to jupyter notebook image

### Details and comments

It might be nice to be able to use the circuit knitting toolbox in our jupyter notebook, so this PR adds it. As there isn't a released version yet, it clones the repo and builds from source (which may or may not be the right way to go about it, open to alternatives here).

### CODE REVIEW

**Comment by psschwei** [comment]
The only stable release was the [initial one](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/releases) from back when the repo was first released, so for now I think the only option is to build off of the main branch if we want to include the CKT now. Once a new release is cut though I agree we should switch over to that. We could also wait to add the CKT until there's a stable release... I don't have a strong opinion either way, so either option works for me.

**Comment by pacomf** [comment]
what do you think @IceKhan13 @caleb-johnson @garrison @jenglick ?

**Comment by caleb-johnson** [comment]
> Perfect scenario would be to have CKT as pypi package so we can install in as dependency passing to program object
> 
> ```python
> Program(
>    ...
>    dependencies=["ckt==0.1.0"]
> )
> ```
> 
> But I do not know exact timeline of release, so maybe it make sense to have it build from source now.
> 
> @caleb-johnson should weight in here

There haven't been any major updates since the initial 0.0.0 release, as we've largely been developing internally. I would try to work off 0.0.0 unless you are having problems.

If you can't get it working with 0.0.0 and don't want to install from the main branch, we plan to release sometime in the next month or so, and we will be on timed releases after that. We treat main as our stable branch, so it wouldn't be the worst thing to install from that branch.

**Comment by garrison** [comment]
> It might be nice to be able to use the circuit knitting toolbox in our jupyter notebook

One potential issue is that ckt depends on cplex, which is not available on all platforms (e.g., ARM).  There is an open PR to fix this at https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/pull/109.  If it would be helpful to you, I would be in favor of cutting a new ckt release (0.1.0) after we merge https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/pull/109, but before we add significant new functionality.

**Comment by psschwei** [comment]
> cutting a new ckt release (0.1.0) 

+1 for me

**Comment by Tansito** [comment]
For me this is a good point from @garrison :

> One potential issue is that ckt depends on cplex, which is not available on all platforms (e.g., ARM).

Right now we are making some progress with M1 chips in `quantum-serverless` and I would wait until that is fixed in `ckt` cause we have people in the team with those chips: cc @pacomf . So from my part I would wait a little bit before introduce it as it is in this PR.

**Comment by psschwei** [comment]
Seems general consensus was to wait for a v0.1 release to add CKT, so going to close this.

**Comment by Tansito** [comment]
Thank you @psschwei to open the discussion anyway. Really appreciate it 🙏

**Comment by caleb-johnson** [comment]
@psschwei the release is coming imminently (should have a release today that resolves this problem and another next week for gate cutting). You *could* reopen and wait

**Comment by psschwei** [comment]
> the release is coming imminently (should have a release today that resolves this problem and another next week for gate cutting)

awesome! will reopen and update the PR when the new version is out

**Comment by garrison** [comment]
circuit-knitting-toolbox 0.1.0 has been released.

**Comment by psschwei** [comment]
Seems like I can't reopen this one for some reason (:shrug:), so will open a new PR instead

**Pull request closed without merging**
