### PR TITLE
Adds requirements file for notebook dependencies

### PR DESCRIPTION
**Pull request by psschwei**
### Summary

Consolidate dependencies for notebook into a single location
Also fixes port-forwarding failure in GHA k8s test

### Details and comments

DRY and all

### CODE REVIEW

**Comment by psschwei** [comment]
Port-forwarding seems very temperamental in GHA... will switch over to something else to stop the failures...

**Comment by IceKhan13** [comment]
Do you want to try to fix ports in this PR?

**Comment by psschwei** [comment]
yeah, I will

**Comment by psschwei** [comment]
@IceKhan13 we are good to go

**Review by IceKhan13 — APPROVED** [review]
let's go! 

We probably need to remove pyscf pedendency from all build, since we are not using them in any of our examples

**Pull request merged**
