### PR TITLE
LocalProvider

### PR DESCRIPTION
**Pull request by akihikokuroda**
### Summary
Add LocalProvider

### CODE REVIEW

**Comment by akihikokuroda** [comment]
@IceKhan13 Am I on the right track?

**Comment by IceKhan13** [comment]
Direction is looking good to me :) 
I also was thinking about this in a same way.

**Comment by akihikokuroda** [comment]
@IceKhan13 Thanks!

**Review by psschwei — COMMENTED** [review]
I got an error when trying to run using local provider:

image

**Comment by akihikokuroda** [comment]
`serverless.upload(pattern)` may be missed to execute?

**Comment by akihikokuroda** [comment]
@psschwei `serverless.upload(pattern)` need to be executed before `run`.  Would you try?

**Comment by psschwei** [comment]
Good catch... (I followed the steps in the issue, which was written before upload was a thing...)

**Comment by psschwei** [comment]
It worked, although I did get a warning when getting the results:

image

**Comment by IceKhan13** [comment]
I think we can raise `NotImplementedException` with message that `LocalProvider` does not support uploaded programs. And ask user to use `run(Program("...", entrypoint="bla.py", working_dir="./asdasd"))`

**Comment by IceKhan13** [comment]
ah, I see how you did it :) feel free to ignore above message

**Comment by akihikokuroda** [comment]
It supports both.  For the new pattern, 'load' must be called before 'run' .  It's the same way with the same way as serverless provider.

**Comment by akihikokuroda** [comment]
I'll look into the warning.  Thanks!

**Comment by akihikokuroda** [comment]
@psschwei The waring should have gone now.

**Review by psschwei — APPROVED** [review]

**Review by IceKhan13 — APPROVED** [review]

**Pull request merged**
