### PR TITLE
user smaller images for initcontainers

### LINKED ISSUE #716: Use smaller images for gateway init containers
### What is the expected enhancement?

from https://github.com/Qiskit-Extensions/quantum-serverless/pull/707#discussion_r1238534767

currently using the ray image, which is 2+ GB... something smaller, like busybox or distroless assuming they have the needed tools, might be more efficient

### PR DESCRIPTION
**Pull request by akihikokuroda**
### Summary
fix #716 

### Details and comments
I picked up images that support both amd64 and arm64 and have necessary packages.

alpine/k8s:1.27.3 - 230 mb
finalgene/openssh:9.1 - 12.5 mb

### CODE REVIEW

**Comment by psschwei** [comment]
I'm a little leery of `finalgene`  as that seems to be just some random person... not blocking, but just figured I'd mention that

**Comment by akihikokuroda** [comment]
I agree.  I couldn't find a good one so far.   We can add the openssl to alpine but I don't want to maintain the image.

**Comment by akihikokuroda** [comment]
I try `registry.access.redhat.com/ubi8/openssl:8.8-3`.

**Comment by psschwei** [comment]
> I don't want to maintain the image

agree, though in a worst case we could add it to the build GHAs to trigger a rebuild on every release (or nightly if that would be better).

But the UBI image looks promising... I'll trade 4MB to trust the maintainer :smile:

**Comment by akihikokuroda** [comment]
The ubi image works.

**Review by psschwei — APPROVED** [review]

**Pull request merged**
