### PR TITLE
add loki data source and ray system dashboard to grafana

### LINKED ISSUE #282: Aggregate logs from ray cluster
### What is the expected behavior?

Aggregate logs from ray cluster.
Workers emit logs, we need to gather them.

Epic https://github.com/Qiskit-Extensions/quantum-serverless/issues/174

### PR DESCRIPTION
**Pull request by akihikokuroda**
### Summary
Closes #282 

### Details and comments

This PR adds the loki data source configuration to Grafara.  It also add preconfigured ray system dashboard.

### CODE REVIEW

**Comment by psschwei** [comment]
Ray dashboard looks good!

image

I did notice that one of the loki logs containers is crashing with an error about "too many open files" making it "unable to create the logs instance"... not exactly sure why that's happening.

Full error message for reference: `ts=2023-03-20T18:37:43.520451861Z caller=main.go:57 level=error msg="error creating the agent server entrypoint" err="unable to apply config for ray/quantum-serverless-loki: unable to create logs instance: failed to make file target manager: too many open files"`

**Comment by akihikokuroda** [comment]
@psschwei Thanks for reviewing.  There are some issues with a dashboard with multiple log panels.  I probably create a  dashboard for each log panel while I investigate the solution.

**Review by psschwei — APPROVED** [review]
Think it's probably fine to merge this and then fix the dashboard issue in a separate PR

**Comment by akihikokuroda** [comment]
@psschwei  I'll do that.  Thanks!

**Pull request merged**
