### PR TITLE
prevent job record override and retry

### PR DESCRIPTION
**Pull request by akihikokuroda**
### Summary
Fix: #946 

### Details and comments
When the job record gets updated with the result by the gateway, the scheduler skips updating the job recode with the new status and lets the next cycle update the record.

### CODE REVIEW

**Comment by IceKhan13** [comment]
Should we add retry or something like that here (save result API) too? 

https://github.com/Qiskit-Extensions/quantum-serverless/blob/db829650b2b9339d650326a84c30257e4848bcbc/gateway/api/views.py#L144

**Comment by akihikokuroda** [comment]
@IceKhan13 The retry is done as a part of the next scheduler cycle.  So we don't need to add any extra code to do it.

**Comment by akihikokuroda** [comment]
@IceKhan13 You are right.  I'll add retry there.

**Comment by akihikokuroda** [comment]
@IceKhan13 The save result API could write the result anyway before.  By adding the `version = IntegerVersionField()` of 'concurrency` in the Job model, it can start raising exceptions.

**Review by Tansito — CHANGES_REQUESTED** [review]
@akihikokuroda @IceKhan13 I was taking a look to the issue and the PR and I would like to propose another solution for this. 

My idea would be to use `updated_fields` to solve the problem:

https://docs.djangoproject.com/en/4.2/ref/models/instances/#specifying-which-fields-to-save

From what I understood the problem is that `save` overrides the entry because we are mostly saving the entire dataset. My proposal would be to just save only those required fields in each section to avoid that undesired override (in this case the `solution`field).

Something like:

```
# in update_jobs_statuses.py line 59
job.save(update_fields=["logs", "env_vars", "status"])

# in views.py line 149
job.save(update_fields=["result"])
```

I see several benefits with this solution versus the proposed one. The first one is that we don't need to play with a new `version` field in the model that I find confuse. And the use of `saved` and the `while` in the middle of the logic that difficult the readability in a code that from my point of view is getting quite complex to follow.

**Comment by akihikokuroda** [comment]
@Tansito It seems good idea.  I can trash this PR and create a new one.  @IceKhan13 WDYT?

**Comment by Tansito** [comment]
I tested this pull request and It's working. I can't say the same from my proposal 😂 

I would say that we can maintain this pull request open in case the another one doesn't solve the problem, Aki. But as you prefer, what it's more confortable for you.

**Comment by IceKhan13** [comment]
@akihikokuroda let's leave this PR and create another one

**Comment by IceKhan13** [comment]
I will just put it on hold for now. If other implementation will work, we can close this one :)

**Comment by akihikokuroda** [comment]
#959 is used to fix the issue.  Closing this.

**Pull request closed without merging**
