### PR TITLE
Increase NGINX body-size

### LINKED ISSUE #818: Increase request payload size
### What is the expected enhancement?

Currently maximum size of uploaded file is set to ~2 mb (which is looks like default for nginx) which is limitation for users as artifact from uploaded programs might have large artifacts.

We need to allow users to upload larger artifact files (around 50 mb).

Probably it is need to be configured in deployment nginx

### PR DESCRIPTION
**Pull request by Tansito**
### Summary

Fix #818 
Co-authored-by: @psschwei 

Confirmed with the infrastructure team and added the required label specified in the issue: `proxy-body-size`.

### CODE REVIEW

**Review by psschwei — APPROVED** [review]

**Review by IceKhan13 — APPROVED** [review]
🚀

**Comment by akihikokuroda** [comment]
I got a little confused with the changes in the value.yaml file change for the local install.  There are 2 ingress instances configurations in the value file.  One is installed with Ray operator and the other is installed as a dependency of the quantum-serferless chart.  The changes make the change in the ingress installed with Ray operator that is not enable for the local install.  The other ingress is enabled for the local install.

**Comment by Tansito** [comment]
Mmm... Which instance for Ray operator do you mean, @akihikokuroda ?

Right now I see two different instances:

- Local NGINX for local development, managed by `nginxIngressControllerEnable`
- NGINX configuration for 3rd party cloud platforms

I admit that there we can have a bit of confuse because depending on the provider we are going to need to change that configuration. I'm totally open to improve that (I think @psschwei mentioned before some ways to fix it).
Sorry, I don't know if I'm followinf here, @akihikokuroda 🙏

**Comment by akihikokuroda** [comment]
@psschwei Yes, it is.

**Pull request merged**
