### PR TITLE
Infra: docker-compose repository

### LINKED ISSUE #552: Unable to connect to gateway in v0.0.9 examples
### Steps to reproduce the problem

Spin up local install: `VERSION=0.0.9 docker-compose --profile full up`
browser -> http://localhost:8888/lab/tree/serverless/running/01_running_program.ipynb
run first two cells (update provider one to use `http://gateway:8000` for the host instead of localhost)

### What is the current behavior?

Returns

```
QuantumServerlessException: 
| Message: Http bad request.
| Code: 400
| Details: {"message":"\n<!doctype html>\n<html lang=\"en\">\n<head>\n  <title>Server Error (500)</title>\n</head>\n<body>\n  <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n"}
```

### What is the expected behavior?

The notebook runs with no error. 

(fwiw, `VERSION=0.0.8 docker-compose --profile full up` works fine, so seems it was something introduced after v0.0.8 was cut)

### PR DESCRIPTION
**Pull request by IceKhan13**
### Summary

Hotfix for local docker-compose setup.

### Details and comments

Gateway and repository has the same application name and same table programs. Therefore migrations in both applications were creating the same table in the same database. Migration passed as it was thinking that those table existed already. 

This PR is a hotfix to make docker-compose with  `full`, `default` and `jupyter` profile work. 
Real fix will be implemented within https://github.com/Qiskit-Extensions/quantum-serverless/issues/555

Closes #552

### CODE REVIEW

**Comment by psschwei** [comment]
I'm still getting the error

**Comment by IceKhan13** [comment]
@psschwei with profile `full`? or without profile?

**Comment by psschwei** [comment]
full

**Comment by psschwei** [comment]
ok, looks like I may have been caching things... deleting and recreating got it working

**Review by psschwei — APPROVED** [review]

**Comment by IceKhan13** [comment]
Tomorrow we will create proper fix :)

**Pull request merged**
